# Generated by Django 2.2 on 2020-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
    ]
