# Generated by Django 2.2 on 2020-07-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_activity',
        ),
    ]
